workspace:
  path: src

pipeline:
  build:
    image: webhippie/hugo:latest
    commands:
      - hugo

  upload:
    image: plugins/s3-sync
    acl: public-read
    region: us-east-1
    bucket: readme.drone.io
    source: public/
    target: /0.5/
    delete: true
    content_type:
      ".svg": image/svg+xml
    when:
      event: push
      branch: release/0.5
